### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by inwitio** [09terp/inwit.io#1]
#### TODO List
- [ ] Optimize for mobile content
- [ ] Add video background
- [ ] Design content elements
- [ ] Get Bitly.com integration
- [ ] Investigate Angular.js
- [ ] Investigate minifying js
- [ ] Add http://maxwellito.github.io/vivus/
